namespace Shared.Players;

public sealed record PlayerDto(
    int Id,
    string Name,
    int Gold,
    int Level,
    int Experience,
    int Food,
    int Attack,
    int MaxHp,
    int CurrentHp,
    string? CurrentEnemyName,
    int? CurrentEnemyMaxHp,
    int? CurrentEnemyCurrentHp,
    int? CurrentEnemyAttack,
    int? CurrentEnemyGoldReward,
    int? CurrentEnemyExperienceReward,
    string CurrentAreaKey,
    string CurrentAreaDisplayName,
    EncounterMetadataDto? CurrentEncounter,
    string PreferredEnemyKey,
    bool PowerStrikeEnabled,
    int PowerStrikeCooldownRemaining,
    DateTime CreatedAt,
    DateTime UpdatedAt);
